### ISSUE TITLE
Why there is no refund transaction type in BEP3?

### ISSUE THREAD

**Issue by fanyongpeng** [binance-chain/BEPs#36]
In BEP3 draft, BNB chain will add 2 transaction types to support HTLC.

1. Hash Timer Locked Transfer (HTLT).
2. Claim Hash Timer Locked (CHTL).

But i am confused how to refund the asset while the time is expired? 

                                          ---KOFO-Fundation

**Comment by HaoyangLiu** [comment]
Refund method will be added soon. I have not update the BEP3 yet. Actually, Binance Chain can automatically refund tokens when the time is expired. But to reduce the impact to performance, we decided to add refund method.

**Comment by fanyongpeng** [comment]
That's great , thanks!
