### ISSUE TITLE
https://github.com/binance-chain/BEPs/blob/master/BEP2.md#532-transfer-tokens does not show transfer fee applicable for asset transfer

### ISSUE THREAD

**Issue by goedzo** [binance-chain/BEPs#47]
Trying to find out the actual BNB tansfer fee required for asset token transfers, but this is nowhere stated and also not clear if we need to provide a fee when doing the transaction. Please add this to the documentation.

**Comment by corollari** [comment]
You can find the value of this fee in [the official documentation](https://docs.binance.org/trading-spec.html#fees).

Given that these fees are meant to be adjusted from time to time I don't think they should be included as part of the BEP, as doing so would require continuous changes on the BEP.

**Comment by SwampMan1983** [comment]
Yes it does need to be included because people new to this and new to buying crypto don’t know to add it and think there coins don’t have value at all! It happened to me.
