### ISSUE TITLE
BEP3 - Ethereum ERC20 token swap.

### ISSUE THREAD

**Issue by patidarmanoj10** [binance-chain/BEPs#54]
As I know some pegged token already launched on Binance.  does it mean that BEP3 is already implemented?   I was wondering if this is already implemented for Ethereum ERC20 token and I can test it.  Please confirm.

**Comment by HaoyangLiu** [comment]
BEP3 is ready, this is the document: https://docs.binance.org/atomic-swap.html#atomic-swap
