### ISSUE TITLE
What is OB and CB ?

### ISSUE THREAD

**Issue by ludete** [binance-chain/BEPs#61]
What's the full name of OB/CB？

When reading the document, I was confused by the sudden abbreviation

https://github.com/binance-chain/BEPs/blob/master/BEP3.md#client-swap-tokens-from-ethereum-to-binance-chain

**Comment by ludete** [comment]
@HaoyangLiu @huangsuyu 

Could you help to answer the question?

**Comment by HaoyangLiu** [comment]
`OB`: peggy Owner address on Binance chain
`CB`: Client address on Binance chain

**Comment by ludete** [comment]
Thank you @HaoyangLiu
